cookietemple_version: '1.4.1 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: idtrack
project_slug_no_hyphen: idtrack
template_version: '2.1.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: theislab
creator_github_username: inecik
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: theislab
full_name: Kemal Inecik
email: k.inecik@gmail.com
project_name: idtrack
project_short_description: ID mapping between different times, databases, genome assemblies.
version: 0.0.3
license: BSD
